### ISSUE TITLE
Node 0.12 Centos?

### ISSUE THREAD

**Issue by mrichard** [nodesource/docker-node#17]
Hi,
Curious why isn't there any io.js or Node 0.12 images for centos?
thanks,

**Comment by wblankenship** [comment]
The purpose of these images (currently) is to track the pre-compiled binaries provided by https://github.com/nodesource/distributions

When those become available in the NodeSource distributions they will show up here :smile:

**Comment by wblankenship** [comment]
To track the progress of this, visit https://github.com/nodesource/distributions/issues/73

**Comment by mrichard** [comment]
ah thanks!
