### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by phillipj** [nodesource/docker-node#18]
Hi there!

Are you still maintaining these dockerfiles? If not do you know of other trusted dockerfiles for node/io?

**Comment by wblankenship** [comment]
Hey @phillipj!

Yes, these are still maintained although the tags are a bit behind. The images that have been released are getting regular updates from upstream, so if you are using a pinned version your image is still up-to-date.

I'll be bringing the most recent versions into the repo ASAP.

**Comment by phillipj** [comment]
That's awesome! Looking forward to more recent versions. Thanks for answering quickly 👍
