### ISSUE TITLE
npm and git depends on ssh

### ISSUE THREAD

**Issue by koresar** [nodesource/docker-node#26]
`package.json` urls like `git+ssh://github...` do not work. Packages can't be installed.

**Comment by wblankenship** [comment]
duplicate of https://github.com/nodesource/docker-node/issues/8

Will deploy new versions this weekend.

**Comment by wblankenship** [comment]
Thanks for opening an issue @koresar, I'll keep you posted on the status through #8 :smile:

**Comment by koresar** [comment]
Thank you.
