### ISSUE TITLE
node v4 for CentOS 7 x86_64

### ISSUE THREAD

**Issue by focusaurus** [nodesource/docker-node#33]
nodesource rpms are available [in pub_4.x/el/7/x86_64](https://rpm.nodesource.com/pub_4.x/el/7/x86_64/) but I don't see any corresponding docker images on dockerhub. Specifically looking for 4.2.1 but anything 4.x would be nice.

**Comment by wblankenship** [comment]
Hey @focusaurus, I added these to the repo earlier this week but they are failing the integration tests.

I've been working on getting the build time down on these so that we can iterate on them faster (currently it takes 8 hours to test!).

I should have something working for you this week.

**Comment by wblankenship** [comment]
Hey @focusaurus, the latest versions of Node are now available for both centos and fedora. Cheers!

**Comment by focusaurus** [comment]
Great, thanks! I see them listed on [hub.docker.com](https://hub.docker.com/r/nodesource/node/) in the HTML but pulling says there is no such tag:

```
docker pull nodesource/centos7:4.2.2
Pulling repository docker.io/nodesource/centos7
Tag 4.2.2 not found in repository docker.io/nodesource/centos7
```

Am I missing a step or something?

**Comment by focusaurus** [comment]
Yeah, hmm, the newer 4.x tags are not listed here: https://hub.docker.com/r/nodesource/centos7/tags/

**Comment by wblankenship** [comment]
Super weird. Pushes to this repository trigger a rebuild of the cenots7-base image, which in turn triggers a rebuild of the centos7 images. The base image completed this morning, but the other images have taken over 6 hours to build. I'll open a support ticket on Docker Hub for this and try and get it resolved.

In the meantime, if this is on your critical path, you can use these images locally via:

1. Clone this repository
2. run `docker build -t "nodesource/centos7-base" .` in `./base/centos/7/
3. run `docker build -t nodesource/centos7:4.2.2` in `/centos/7/node/4.2.2/`

I'll post updates here as they come.

**Comment by wblankenship** [comment]
![docker_images1](https://cloud.githubusercontent.com/assets/1081565/11126063/2ec2d362-893b-11e5-88ea-9d6587e73aa3.png)

v4 should now be available.

**Comment by focusaurus** [comment]
Yup, looks good from my side, too. Thanks!

**Comment by wblankenship** [comment]
:heart:
