### ISSUE TITLE
Tag 4.2.2 not found in repository docker.io/nodesource/trusty

### ISSUE THREAD

**Issue by d6u** [nodesource/docker-node#37]
Seems like the image is not up to date on docker hub?

**Comment by wblankenship** [comment]
The upstream repo added a dependency causing the build to fail. I've added the dep and am running the integration tests locally. Once they pass I'll push the changes to this repo which should trigger the builds on hub.

Will post updates here.

**Comment by wblankenship** [comment]
This should be fixed :-)

![Uploading docker_images1.png…]()

Please reopen if you are still experiencing issues :smile:

**Comment by d6u** [comment]
Thanks!
