### ISSUE TITLE
Node v5.2.0

### ISSUE THREAD

**Issue by billinghamj** [nodesource/docker-node#41]
:smile: 

Given how rapidly new Node versions are being released now, I think it probably would be worth trying to automate this process at least somewhat.

**Comment by wblankenship** [comment]
Hey @billinghamj!

The builds for 5.2.0 and 5.3.0 are running on the registry now.

Yes, the process of cutting a new release is rather cumbersome right now. Unfortunately, if we want to keep our Automated Build status on the Docker registry, we are as automated as we can be.

Our building and testing process is entirely automated up until the point of updating the registry itself. The Docker API doesn't expose an endpoint for updating automated builds, so we have a tool that generates the set of mutations necessary to bring the registry back into parity with our GitHub repository prior to triggering a rebuild on the registry.

The process is essentially `./tools/build.sh` which gives us the set of mutations that looks something like:

![registry_diff](https://cloud.githubusercontent.com/assets/1081565/11906474/d5cc447e-a59a-11e5-94b3-f8b6ac71dec5.png)

We then manually update the registry (an extremely tedious task), and merge the PR here which triggers the rebuild.

We are looking into ways that could replace this step, and fully automate the process.This would reduce our turnaround time from days to hours.  We should have some new information for you soon :smile:
