### ISSUE TITLE
centos7:4.2.3

### ISSUE THREAD

**Issue by austo** [nodesource/docker-node#42]
Node 4.2.3 on Centos 7 fails:
```
$ docker pull nodesource/centos7:4.2.3
Pulling repository docker.io/nodesource/centos7
Tag 4.2.3 not found in repository docker.io/nodesource/centos7
```

Works on 4.2.2

**Comment by wblankenship** [comment]
Thanks you for reporting @austo.

It appears that `libicu` was missing from our public base images.

I've made the adjustments necessary and retriggered the builds. They should be available in a few hours.
