### ISSUE TITLE
How to use with Meteor?

### ISSUE THREAD

**Issue by katopz** [nodesource/docker-node#49]
Hi guys,

I'm using [Meteor](https://www.meteor.com/) and deploy to Ububtu 14 via [mupx](https://github.com/arunoda/meteor-up/tree/mupx#) which also using [docker](https://github.com/meteorhacks/meteord) and try to hook N|Solid in but I'm going no where. (yes I'm noob)

Any hint?

**Comment by cronopio** [comment]
Hi @katopz 

The main issue is that Meteor is built using Node.js version `0.10.x` and N|Solid extends the latest version of Node.js. Right now using Node.js version `4.2.4`.

Let us know if you have more questions about this topic.

**Comment by katopz** [comment]
Hi @cronopio 

Let's say if someone [magically can make a use of 4.x versions](https://github.com/meteor/meteor/issues/5124)
What's my next step? 

Thanks

**Comment by retrohacker** [comment]
Hey @katopz, 

That sounds really cool! Unfortunately, the NodeSource Node.js Docker Images were not designed with this use case in mind.

While I would be interested in hearing about your success with using/modifying these images for Mupx, these were designed to be deployed directly on the Docker Engine. This may better be posed as a question for the Meteor or Mupx teams in using third-party Docker images with their tooling.
