### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by billinghamj** [nodesource/docker-node#53]
Now that the current Ubuntu LTS is 16.04 ("Xenial Xerus"), could you possibly add it to your list of supported OSes?

Thanks!

**Comment by retrohacker** [comment]
Hey @billinghamj!

The short answer is "Yes!"

The long answer is, I'm building automated infrastructure that will magically detect these things and ship them for us without human intervention. This means new OS releases will become available within hours of them showing up in the NodeSource repos as opposed to within weeks.

The automated bits for this repo are done here: https://github.com/nodesource/docker-node/blob/automate/tools/get_releases.sh

I'm working on automating the build infrastructure now so the machines will be provisioned and kick off builds when changes are detected upstream. This may take a few days, but it's on the horizon!

**Comment by mansona** [comment]
Any progress on this? Need any help to get it running?

**Comment by retrohacker** [comment]
Hey @mansona 

Sorry, I've been AFK for my honeymoon. The automated tooling should be picking this up, strange that it isn't. Taking a look today.

**Comment by billinghamj** [comment]
@retrohacker Did you manage to find out why it isn't being pulled in? :)

**Comment by mansona** [comment]
@retrohacker is the automated tooling opensource or on github? might be worth bringing the discussion to that repo if there is anything to be gained from our help 😄 

(also congrats 🎉 🎊 )

**Comment by retrohacker** [comment]
Thanks @mansona!

And the tooling is opensource, it lives at https://github.com/nodesource/docker-node/blob/master/tools/build.sh

Running `build.sh` kicks off the chain of events that lead to a fresh batch of Docker images :smile:

**Comment by billinghamj** [comment]
So all that's needed is to just add three lines to the gen-dists.sh file...?

**Comment by billinghamj** [comment]
See #54

**Comment by retrohacker** [comment]
@billinghamj thank you for all of your help here!

This landed!

https://hub.docker.com/r/nodesource/xenial/
https://hub.docker.com/r/nodesource/wily/
https://hub.docker.com/r/nodesource/fedora23/
https://hub.docker.com/r/nodesource/fedora24/

all shipped late last night!

**Comment by retrohacker** [comment]
:tada:

**Comment by billinghamj** [comment]
👍
