### ISSUE TITLE
NODE_ENV is set to production by default in image

### ISSUE THREAD

**Issue by DCRichards** [nodesource/docker-node#61]
## Description

I am currently using `nodesource/jessie:0.10.46` for a (legacy!) project, it took a while of investigating missing devDependencies to realise that `NODE_ENV=production` was set by default.

Should this be the choice of the user to enable production, as Docker is often used in development and for testing/CI etc?

**Comment by chrislea** [comment]
We don't set that variable on newer versions of Node, but 0.10.x has been EOL for some time now and won't be receiving any further updates.
