### ISSUE TITLE
apt-get --no-install-recommends

### ISSUE THREAD

**Issue by wblankenship** [nodesource/docker-node#8]
Are the recommended packages necessary?

**Comment by lovell** [comment]
Hi @wblankenship, thanks for maintaining these Dockerfiles!

The `git` package has an [recommends](http://packages.ubuntu.com/vivid/git) dependency on `ssh-client`.

The use of [Git URLs as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) in `package.json` can result in a failed attempt to use the missing `ssh` command when running `npm install`. This is always the case when using the common Github `user/repo` format.

Perhaps installing `ssh-client` via `apt-get` in the Dockerfile would be enough for this example?

**Comment by wblankenship** [comment]
Hey @lovell,

You are absolutely right. We should be able to add `ssh-client` to this line to fix for debian and ubuntu, https://github.com/nodesource/docker-node/blob/master/dockerfiles/debian.js#L48

Will take a look at this for our RHEL flavored images as well.

**Comment by lovell** [comment]
Thanks @wblankenship.

Whilst you're looking at this, I think the RHEL images also need the equivalent of `build-essential` to be able to compile native addons, perhaps by including (the dependency tree of) a package like `g++`.

**Comment by wblankenship** [comment]
Hey @lovell and @koresar,

This repo had quickly become unweildy. I just landed a PR (https://github.com/nodesource/docker-node/pull/34) that greatly reduced the build times for running integration tests locally.

I've got a proposal for adding ssh-client and the equivalent to build-essentials, just waiting for the tests to pass and will open a PR before the EOD.

**Comment by koresar** [comment]
I wish GitHub had the "reactions" feature of the Slack. In other words -
:+1:

**Comment by lovell** [comment]
Great, thanks both!
